---
repos:

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.46.0
    hooks:
      - id: terraform_fmt

  #- repo: https://github.com/bridgecrewio/checkov.git
  #  rev: 1.0.811
  #  hooks:
  #    - id: checkov
  #      name: checkov
  #      entry: checkov -d . --framework terraform --quiet --skip-check CKV_AWS_7,CKV_AWS_8,CKV_AWS_18,CKV_AWS_24,CKV_AWS_26,CKV_AWS_27,CKV_AWS_28,CKV_AWS_33,CKV_AWS_50,CKV_AWS_51,CKV_AWS_52,CKV_AWS_59,CKV_AWS_79,CKV_AWS_91,CKV_AWS_103

  #- repo: local
  #  hooks:
  #    - id: tflint
  #      name: Check Terraform configuration files with TFLint
  #      entry: scripts/tflint.sh
  #      language: script
  #      files: \.tf$
  #      exclude: (.terraform|.github).*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [--branch, master]
